# Generated by Django 5.1.7 on 2025-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioApp', '0002_reference_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
