# Generated by Django 5.1.7 on 2025-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioApp', '0004_customuser_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.CharField(choices=[('images/1.png', 'Background 1'), ('images/2.png', 'Background 2'), ('images/3.png', 'Background 3'), ('images/4.png', 'Background 4')], default='images/1.png', max_length=255),
        ),
    ]
